config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  resources :trips do
    resources :locations do
      resources :addresses
    end  
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :trip
  has_many :addresses, dependent: :destroy
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :locations
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @address = Address.all 
  end

  def show
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.create(address_params)
    redirect_to addresses_path
  end

  def edit
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    
  end

  def edit
  end

  def show
  end

  def new
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
    redirect_to trips_path
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    redirect_to trips_path
  end

  def destroy
    @trip = Trip.destroy(params[:id])
    redirect_to trips_path
  end

  private
    def trip_params
      params.require(:trip).permit(:name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br />
  <%= f.label :start %>
  <%= f.text_field :start, placeholder: "Start" %>
  <br />
  <%= f.label :end %>
  <%= f.text_field :end, placeholder: "End" %>
  <br />
  <%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing: <%= @trip.name %></h1>
<hr />
<%= render(partial: "form") %>

app/views/trips/index.html.erb
<h1>All Trips</h1>
<hr />

<% @trips.each do |trip| %>
  <h3> <%= link_to trip.name, trip_path(trip) %> 
  </h3>


    <button type="button">
    <%= link_to "Delete", trip_path(trip), method: :delete, data:  {confirm: "Are you sure you want to delte this trip?"} %> 
    </button>
    <button type="button">
    <%= link_to "Edit", edit_trip_path(trip) %>
    </button> 
<% end %>

<button type="button">
<%= link_to "Create Trip", new_trip_path %>
</button>

app/views/trips/new.html.erb
<h1>Create new trip</h1>
<hr />
<%= render(partial: "form") %>

app/views/trips/show.html.erb
<h1>Trips</h1>
<hr />